# Generated by Django 6.1.1 on 2026-10-06 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=128)),
                ('tipo_usuario', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('EMPRESA', 'Empresa Inmobiliaria'), ('AGENTE', 'Agente Inmobiliario'), ('ADMIN', 'Administrador')], max_length=20)),
                ('estado_activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaInmobiliaria',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Knock2Door.usuario')),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('nombre_fantasia', models.CharField(max_length=150)),
                ('telefono_contacto', models.CharField(max_length=25)),
                ('direccion_comercial', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Knock2Door.usuario')),
                ('rut_dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=25, unique=True)),
                ('tipo_inmueble', models.CharField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('TERRENO', 'Terreno'), ('OFICINA', 'Oficina'), ('BODEGA', 'Bodega')], max_length=20)),
                ('tipo_operacion', models.CharField(choices=[('VENTA', 'Venta'), ('ARRIENDO', 'Arriendo'), ('AMBOS', 'Ambos')], max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna_ciudad', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0)),
                ('superficie_m2', models.FloatField()),
                ('es_publica', models.BooleanField(default=True)),
                ('estado_propiedad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADA', 'Reservada'), ('ARRENDADA', 'Arrendada'), ('VENDIDA', 'Vendida'), ('INACTIVA', 'Inactiva')], default='DISPONIBLE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agente_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_asignadas', to='Knock2Door.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario_cambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knock2Door.usuario')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knock2Door.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('VENTA', 'Venta'), ('ARRIENDO', 'Arriendo')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado_contrato', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VIGENTE', 'Vigente'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_agente', to='Knock2Door.usuario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_cliente', to='Knock2Door.usuario')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knock2Door.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_propiedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knock2Door.propiedad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knock2Door.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knock2Door.rol'),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('estado_visita', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada')], default='PENDIENTE', max_length=20)),
                ('comentarios_agente', models.TextField(blank=True, max_length=500, null=True)),
                ('calificacion_cliente', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_agente', to='Knock2Door.usuario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_cliente', to='Knock2Door.usuario')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knock2Door.propiedad')),
            ],
        ),
    ]
